Enable github actions
Github actions were not being triggered due to the fact that it was restricted to branch named `master`.    Increased the scope for github actions by adding more branches.

Freeze pandas at 1.1.5, for now.  I think that is what is causing the
nan errors.

This wass causing nan to be returned for data calls

=================================== FAILURES
===================================
______________________________ test_usgs_get_data
______________________________

    def test_usgs_get_data():
        synthesizer =
register(['basin3d.plugins.usgs.USGSDataSourcePlugin'])
        usgs_data = get_timeseries_data(
            synthesizer=synthesizer,
monitoring_features=["USGS-09110000"],
            observed_property_variables=['RDC', 'WT'],
start_date='2019-10-25', end_date='2019-10-28')
        usgs_df = usgs_data.data
        usgs_metadata = usgs_data.metadata_store

        # check the dataframe
        assert isinstance(usgs_df, pd.DataFrame) is True
        for column_name in list(usgs_df.columns):
            assert column_name in ['TIMESTAMP', 'USGS-09110000__RDC',
'USGS-09110000__WT']
        assert usgs_df.shape == (4, 3)
        alpha_data = usgs_df.get('USGS-09110000__RDC')
>       assert list(alpha_data.values) == [4.2475270499999995,
4.219210203, 4.134259662, 4.332477591]
E       assert [nan, nan, nan, nan] == [4.2475270499999995, 4.219210203,
4.134259662, 4.332477591]
E         At index 0 diff: nan != 4.2475270499999995
E         Full diff:
E         - [4.2475270499999995, 4.219210203, 4.134259662, 4.332477591]
E         + [nan, nan, nan, nan]

tests/test_plugins_usgs.py:135: AssertionError
___________________________ test_get_timeseries_data
___________________________

    def test_get_timeseries_data():
        synthesizer =
register(['tests.testplugins.alpha.AlphaSourcePlugin'])

        # missing argument
        with pytest.raises(SynthesisException):
            get_timeseries_data(synthesizer=synthesizer,
                                monitoring_features=[],
observed_property_variables=['ACT'], start_date='2019-01-01')

        # missing required parameter
        with pytest.raises(SynthesisException):
            get_timeseries_data(synthesizer=synthesizer,
                                observed_property_variables=['ACT'],
start_date='2019-01-01')

        alpha_data = get_timeseries_data(
            synthesizer=synthesizer,
            monitoring_features=['A-1', 'A-2', 'A-3'],
observed_property_variables=['ACT', 'Al'], start_date='2016-02-01')
        alpha_df = alpha_data.data
        alpha_metadata = alpha_data.metadata_store
        alpha_metadata_df = alpha_data.metadata_dataframe

        # check the dataframe
        assert isinstance(alpha_df, pd.DataFrame) is True
        assert list(alpha_df.columns) == ['TIMESTAMP', 'A-1__ACT',
'A-2__ACT']
        assert alpha_df.shape == (9, 3)
        alpha_data = alpha_df.get('A-1__ACT')
>       assert list(alpha_data.values) == [num * 0.3454 for num in
range(1, 10)]
E       assert [nan, nan, nan, nan, nan, nan, nan, nan, nan] ==
[0.3454,\n 0.6908,\n 1.0362,\n 1.3816,\n 1.7269999999999999,\n 2.0724,\n
2.4177999999999997,\n 2.7632,\n 3.1086]
E         At index 0 diff: nan != 0.3454
E         Full diff:
E           [
E         -  0.3454,
E         -  0.6908,
E         -  1.0362,
E         -  1.3816,
E         -  1.7269999999999999,
E         -  2.0724,
E         -  2.4177999999999997,
E         -  2.7632,
E         -  3.1086,
E         +  nan,
E         +  nan,
E         +  nan,
E         +  nan,
E         +  nan,
E         +  nan,
E         +  nan,
E         +  nan,
E         +  nan,
E           ]

tests/test_synthesis.py:155: AssertionError